<section id="filetree" data-searchable data-search="file tree structure folder layout">
    <div class="section-header">
        <span class="section-icon">📁</span>
        <div>
            <h2>File tree</h2>
            <p>What lives where after <code>/setup-claude</code> runs.</p>
        </div>
    </div>

    <div class="codeblock">
        <pre>wp-content/themes/&lt;theme&gt;/             ← workspace root
├── README.md                            ← personalized daily reference (generated by setup)
├── brand.config.json                    ← single source of truth for brand identity
│                                          (phone, email, colors, fonts — read by aiims_brand())
│
├── briefs/                              ← section briefs (auto-created by Claude)
│   ├── _template.md
│   └── &lt;section&gt;.md
│
├── .claude/                             ← Claude config (don't touch unless retro)
│   ├── CLAUDE.md                        ← master rules (Claude reads on every session)
│   ├── cheatsheet/                      ← THIS cheatsheet (Cowork + Code reference)
│   │   ├── index.php
│   │   ├── .env                         ← Gemini API key (gitignored)
│   │   ├── partials/                    ← page sections
│   │   ├── api/polish.php               ← Gemini proxy
│   │   └── assets/
│   ├── skills/                          ← workflow recipes
│   ├── agents/                          ← specialists (frontend-builder, acf-architect, etc.)
│   ├── commands/                        ← slash commands
│   └── settings.local.json              ← bash + git permissions
│
├── tailwind/
│   └── tailwind-theme.css               ← brand tokens here (@theme block)
│
├── javascript/
│   └── script.js                        ← scroll animations (data-reveal handler)
│
└── theme/                               ← actual WordPress theme
    ├── inc/
    │   ├── helpers.php                  ← aiims_img() + aiims_svg_kses() + aiims_brand()
    │   ├── acf-setup.php                ← Local JSON load + phone validation
    │   ├── custom-functions.php         ← hub: requires helpers + acf + seed/upload loaders
    │   ├── seed-&lt;slug&gt;.php               ← one-shot ACF seeders (auto-load, self-delete)
    │   └── upload-&lt;slug&gt;.php             ← one-shot media uploaders (auto-load, self-delete)
    │
    ├── templates/
    │   ├── template-homepage.php        ← front page (rigid, $home_sections array)
    │   ├── template-default.php         ← universal (Flexible Content driver)
    │   └── parts/
    │       ├── section-_example.php     ← reference (don't include)
    │       └── section-&lt;slug&gt;.php       ← built by Claude, one per section
    │
    ├── acf-json/                        ← ACF Local JSON (git-tracked)
    │   ├── group_default_template_sections.json
    │   └── group_&lt;slug&gt;.json
    │
    └── assets/
        ├── images/&lt;section&gt;/            ← static-phase images (cleared by /upload-images)
        └── icons/                       ← theme-wide static SVGs</pre>
    </div>

    <h3 style="margin-top: var(--space-5);">Key conventions</h3>
    <ul>
        <li><strong>ACF layout names use underscores:</strong> <code>home_hero</code></li>
        <li><strong>Section file names use dashes:</strong> <code>section-home-hero.php</code></li>
        <li><strong>The default template translates between them</strong> automatically (loop does <code>str_replace('_', '-', ...)</code>).</li>
        <li><strong><code>aiims_*</code> is the fixed helper namespace</strong> — not derived from theme slug. AIIMS Group convention.</li>
        <li><strong>Seeders and uploaders auto-load</strong> via the glob in <code>inc/custom-functions.php</code>. Drop a file in <code>inc/seed-&lt;slug&gt;.php</code> and it's live.</li>
    </ul>
</section>
